(package "aws"
         "0.1.0"
         "AWS Toolkit")

(website-url "https://github.com/jcs090218/aws-toolkit-emacs")
(keywords "aws" "convenience")

(package-file "aws.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "27.1")
(depends-on "lsp-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
